# Base image
FROM node:12-alpine

# Set working directory
WORKDIR /app

# Copy app files
COPY . .

# Install dependencies 
RUN npm install @pact-foundation/pact
RUN npm install -D jest supertest

# Expose port for mock server
EXPOSE 1234 

# Environment variables 
ENV HOST=localhost
ENV PORT=1234

# Command to start app
CMD ["node", "pact-test-runner.js"]